### ISSUE TITLE
Add Support for selection from to jump

### ISSUE THREAD

**Issue by Visual-Dawg** [DavidLGoldberg/jumpy2#11]
When refactoring I sometimes want to move or cut a block of code.
Currently I am using the mouse or `Shift` + `Arrows` to select it.

But with Jumpy it would be so much faster.

Adding something like a modifier key to the jump which would select all text between the jump start and end would be really neat.

**Comment by DavidLGoldberg** [comment]
If I am understanding you correctly, I had this feature working in the Atom version.  Unfortunately, when I tried implementing this in VS Code I hit some hurdles.  Maybe the API opened up or there was something I missed,  I  *do* intend to give this another try one day.

The way the Atom one worked btw was a bit simpler, if you were already in selection mode it just stayed in selection.  I used to use it all the time :(

ATM, I use vim mode + jumpy2 and, I sort of wish I didn't have to do *anything* on the jumpy end at all for either 'v' (vim's visual mode) or even for the built in vscode selection.  But unfortunately, I/someone has to add some custom code.

**Comment by Visual-Dawg** [comment]
Yes, you understood me :D
I found [this](https://github.com/metaseed/metaGo/blob/master/src/metaJump/README.md#metajump) extension which is able to do that. Maybe it can help someone to implement it.

Personally, I will use the other extension, because it has a ton of features (no need to reinvent the wheel)

**Comment by DavidLGoldberg** [comment]
Oh, that's a cool extension.  I've seen it before, seems a little too complicated for me.  Along the lines of vim motion, easy motion etc.

**Comment by Visual-Dawg** [comment]
Okay, I am using VSCode with the NeoVim integration now. Wish me luck :D

**Comment by DavidLGoldberg** [comment]
Why did you close this?  This *is* a feature I still want to implement.  It implemented it pretty nicely in Jumpy (Atom).  Just ran into issues earlier on with vscode, so tabled it for later.  I will be getting to it soon for sure.  Are you trying Jumpy2 with the NeoVim?  I was able to get it to work (see docs), although not this particular feature of course.  I had issues with the neovim implementation though, so while I still use it in the terminal/cli, I use the more standard VimMode with VSCode.

**Comment by Visual-Dawg** [comment]
I didnt thought about it, I just closed it lol.
I am not using it with Neovim, for that I use the `leap` plugin.

But if you want I can also test it with Neovim

**Comment by DavidLGoldberg** [comment]
What I meant was the vscode+neovim integration via https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim

Last year at release time, I tested jumpy2 with it as well. I was able to get all of the jumpy2 related features to work with it.

**Comment by DavidLGoldberg** [comment]
@Visual-Dawg 1.4.0 has this now.
