### ISSUE TITLE
[Feature] Jump and bookmarks or memoize previous jumps

### ISSUE THREAD

**Issue by leobastiani** [DavidLGoldberg/jumpy2#44]
I'm going to propose this simple feature which memoize or bookmarks previous successful jumps

For example
I jumped to `bc`, then, if I'm editing another file or in the same file, `bc` will jump to the same place like if I had bookmarked
Here's an implementation https://github.com/DavidLGoldberg/jumpy2/commit/45b4de809a6c53a42a200b47eb4d9a5acfa8e0df

It could be a settings that can be true or false

What do you think?

**Comment by DavidLGoldberg** [comment]
Hi, just seeing this now.  I'll take a look!

**Comment by DavidLGoldberg** [comment]
BTW, do you use vsc's 'back' functionality?  I have it bound to backspace and shift+backspace as mentioned in the docs.  Is the goal to create a 'mark'? Like in vi/vim?

I'll take a look at the code and run it.  Thanks!

**Comment by leobastiani** [comment]
Thank you

I'm not a vim person, although I use this shortcut as `ctrl+minus` and `ctrl+shift+minus`

> Is the goal to create a 'mark'?

It actually just a mental mark, so when you first jump to `gm` first time, you will know that `gm` will jump to that position again and you don't have to look to the screen when you want to jump back

**Comment by DavidLGoldberg** [comment]
Hey, would you be able to push it up to your fork and create a PR?  I still have to execute it.  If you could possibly rebase off of the new main, We pushed 2 features.

**Comment by DavidLGoldberg** [comment]
Closing because I think this will cause a bit of cognitive dissonance...

I try to use VSC's back and forward buttons for this.  (Although lately, they seemed to have changed and not been having as great success with it.
