### ISSUE TITLE
wrong lineheight

### ISSUE THREAD

**Issue by kwen8** [DavidLGoldberg/jumpy2#61]
![WX20240607-095353](https://github.com/DavidLGoldberg/jumpy2/assets/13549472/d2f44698-1221-48fc-b445-642704a4c08c)

i use mac
FontSize: 12
FontFamily: Monaco

Editor Theme: Material Theme

**Comment by DavidLGoldberg** [comment]
I'll take a look.  What version vs code and jumpy2?

**Comment by kwen8** [comment]
> I'll take a look. What version vs code and jumpy2?

vs code version: 1.90.0
jumpy2: v1.5.2

**Comment by DavidLGoldberg** [comment]
Hey, sorry for the delay on this.

Had to work on some broken build stuff.

Looks like you made some progress, but to be clear you're talking about this right:
https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme

And then you followed:
{
    // Controls the line height. Use 0 to compute the lineHeight from the fontSize.
    "editor.lineHeight": 28,
    // Enables font ligatures
    "editor.fontLigatures": "'ss01','ss05','dlig'",
    // Controls if file decorations should use badges.
    "explorer.decorations.badges": false
}

Right?  I have been thinking more about lineHeights in general lately, So I might want this to work as well.

I was able to reproduce some quirkiness yeah.  I'll take a look.

**Comment by DavidLGoldberg** [comment]
Hi, Fix is in `#main` I will probably release it this weekend.

**Comment by DavidLGoldberg** [comment]
Released.
