### ISSUE TITLE
[Feature] Try to alternate hands when assigning codes to locations

### ISSUE THREAD

**Issue by typecasto** [DavidLGoldberg/jumpy2#8]
When assigning codes to locations, first assign all the codes where each letter is on a different hand (e.g. go through `fj`, `me`, `ic`, etc. before using same handed codes like `fr`, `gt`, and `dx`, assuming qwerty layout) instead of just assigning them in order. This would make jumping around feel much quicker since I don't have to move the same hand twice.

**Comment by DavidLGoldberg** [comment]
Thanks for addressing this.  This has come up before in the Atom version etc.

I'm not really interested in doing this.  If someone else is, and the code is minimal, I would *consider* merging it.

There is a custom key feature that some people prefer a smaller set of easier to type keys.  I'm not a fan of that, personally. I prefer my labels in order.

It's a good idea, and would probably help a bit, but I think there's lower-hanging fruit to work on.
